name: Inm_Family_bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,6,8,9,11,14,21,22 * * *'
  
env:
  Inm_API_KEY: ${{secrets.INM_API_KEY}}
  Inm_API_KEY_SECRET: ${{secrets.INM_API_KEY_SECRET}}
  Inm_ACCESS_TOKEN: ${{secrets.INM_ACCESS_TOKEN}}
  Inm_ACCESS_TOKEN_SECRET: ${{secrets.INM_ACCESS_TOKEN_SECRET}}
  Inm_BEARER_TOKEN: ${{secrets.INM_BEARER_TOKEN}}

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python main.py
